name = "lean_refactor_v4_29"
version = "0.1.0"

[[require]]
name = "Arklib"
git = "https://github.com/Verified-zkEVM/ArkLib"
rev = "de71a9dfd2f5a343e8895517b7efe857d9f1ce5c"

[[require]]
name = "Physlib"
git = "https://github.com/leanprover-community/physlib"
rev = "7dc032ecb8fc4621893c52026c0a7a6f19383198"
