name = "lean_refactor_v4_27"
version = "0.1.0"

[[require]]
name = "Strata"
git = "https://github.com/strata-org/Strata"
rev = "4348c65a93a3b57b1a4541991ed2d2fcdd9fa35d"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.27.0"
